# -*- coding: utf-8 -*-
"""Hangman Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNwMFdaqQKJDivuTdNi__-0Ong7TyuWn

#Hangman Final

#The Import Function
Some functions have to be imported into a python program for additional functionality.
"""

import random #We will use this library to choose a random word from the list

#Word list to use in the game

word_list = ["planets","refrigerator","bicycle","cardboard","telephone","cabinet","tiger","elephant","penguin"]

#Use the random library with the 'choice' method to pick a random word
random_word = random.choice(word_list)

print(random_word)

"""#Changing the way the chosen word is displayed.
We want the word to be displayed as a series of blanks. The best way to display this is probably by using the underscore character in place of the letter.

To do this we need to understand something about the string data type. The string data type is "*iterable*". Just like lists we can get the length of the string, loop through each element, and perform functions on those elements.

Python gives each character in the string an index number starting with zero. You can also start from the end of the string by using negative integers starting with one.

String:  P  y  t  h  o  n

Index:   0  1  2  3  4  5

Negative:-6 -5 -4 -3 -2 -1

In this example using the string "Python". If we wanted to get the 3rd letter of the string in our program we would type:



```
the_string[2]
```



---
References:

https://www.w3schools.com/python/python_strings.asp

https://www.w3schools.com/python/python_strings_slicing.asp

"""

#example using our word
print(f'The word chosen is: {random_word}')

print("Loop through each character and show it on the screen")
#loop through each character in the word
for a_letter in random_word:
  #print each letter
  print(a_letter)

print("-" * 100)
print("Now let's show each letter as a blank")

#loop through each character and show as a blank (using the underscore character)

for a_letter in random_word:
  print("_")

print("-" * 100)
print("We don't want seperate lines for each blank, so let's fix the format")

#show each character as an underscore but without a new line
for a_letter in random_word:
  print("_", end=" ")


"""Using the optional "end=" after the variables in the print function
   lets us use a space instead of a new line after each letter in the word"""

"""#Guessing the letters

This will be the main playable part of the game. The player will guess letters and our program will have to figure out if that letter is in the word.

We can us the "in" keyword to check if that is true.

"""

#ask the user to guess a letter and assign it to a variable
the_guess = input("Guess a letter: ")

#check if the letter is in the word
if the_guess in random_word:
  print("That letter is in the word")
else:
  print("That letter is not in the word")

"""#Displaying the letter to the player in the right place
If the letter is in the word we want to show the player where exactly that word appears. If it is not in the word it will be helpful to the player to keep track of incorrect guesses. We need to combine our code from the previous steps.
"""

#show each character as an underscore but without a new line
for a_letter in random_word:
  print("_", end=" ")


#One more print for a new line
print(" ")

the_guess = input("Guess a letter: ")

#check if the letter is in the word
if the_guess in random_word:
  print("That letter is in the word")
  #we will assign the good_guess variable to the the_guess so we can check it
  good_guess = the_guess
else:
  print("That letter is not in the word")

#this time we will check if our letter is a good guess and show the letter
#instead of an underscore

for a_letter in random_word:
  if good_guess == a_letter:
    print(good_guess, end=" ")
  else:
    print("_", end=" ")

"""#Loops and Functions
We have reached the point where we need to start thinking about the parts of our program that have repeated statements or actions that will be performed multiple times over and over.

For example: The player will have six guesses to possibly win, they should also be able to guess the whole word and the end of those guess. We will check and keep track of their guess at least six times. Do we intend to copy and paste the code over and over again six or seven times, manually changing the name of the variables to reflect each guess. ie: *good_guess1*, *good_guess2*, etc

This is not optimal for several reasons:
1. It's going to be very confusing to read
2. This will make the code hard to maintin. If we have to change something in the way the code functions we will have to do it multiple times.
3. It will make the program much larger and more complex than neccessary.

We have already used loops to display the letters


```
for a_letter in random_word:
   print(a_letter)
```
as opposed to
```
print(random_word[0])
print(random_word[1])
print(random_word[2])
print(random_word[3])
print(random_word[4])
print(random_word[5])
print(random_word[6])
print(random_word[7])
```
The code will produce the same result. But the first example is much better in many ways.

We basically have all the steps we need to build the game. Let's put some of our repeatable steps in functions and loops and finish the program.

###Setup the game and create a function that will automate displaying the letters

In Python we create a function by starting the line with the letters "*def*". This is short for the word "*define*"

Statements inside the function are indented from the left side.



```
def function_name():
  do something
  do something else
  if some test is true
    do this
  else:
    do something else

```


In our previous code, we iterated through the string a ran a print statement for each "_" or guessed letter.

In this code we are going to be a little more concise and learn a couple of shortcuts.

To simplify the code, we will use a single string and add characters to it as needed. Consider the code below.
"""

#Create and empty string variable
#
some_string = ""
#Add a letter to the string

some_string = some_string + "a"

print("Adding a letter:--> " + some_string)



#Add a bunch of letters to the string
some_string = ""

for item in "abcdefghijklmnopqrstuvwxyz":
  some_string = some_string + item

print("The longway:---> " + some_string)

#Shortcut way
some_string = ""

for item in "abcdefghijklmnopqrstuvwxyz":
  some_string += item

print("The shortcut:---> " + some_string)

"""We can use this trick to build a string to output instead of looping through the word over and over.


"""

display_string = ""

for a_letter in "ChosenWord":
  display_string += a_letter + " "

print(display_string)

"""Now let's add some user input, use an **if** statement to check if the letter is a good guess, and loop the results to see how it works.
We will use a while loop that will loop forever until a certain number is reached.



"""

some_word = "python"

attempts = 6

while attempts > 0:

  the_guess = input("Guess a letter: ")

  display_string = ""
  for a_letter in some_word:
    if the_guess == a_letter:
      display_string += the_guess + " "
    else:
      display_string += "_ "

  print(display_string)

  attempts -= 1 #Like using the string, this is a shortcut for attempts = attempts - 1

import random





def display_word(word_to_guess, guessed_letters):

  display_string = ""

  for a_letter in word_to_guess:

    if a_letter in guessed_letters:

      display_string += a_letter + " "

    else:

      display_string += "_ "

  return display_string.strip()

def hangman():

  #Setup base game variables
  attempts = 6 #The number of guess attempts per word

  word_list = ["planets","refrigerator","bicycle","cardboard","telephone","cabinet","tiger","elephant","penguin"]

  the_word = random.choice(word_list) #pick a random word

  guessed_letters = set() #create an empty set for guesses



  print("Debug: " + the_word)

  #Loop for guessing letters
  #
  while attempts > 0:

    print("Attempts remaining: " + str(attempts))


    the_guess = input("Guess a letter: ")

    guessed_letters.add(the_guess)

    print(display_word(the_word, guessed_letters))

    attempts -= 1

  #End of the loop, one final guess
  #
  final_guess = input("Guess the word: ")

  if final_guess == the_word:

    print("You win!")

  else:

    print("You lose!")

  #Choice to play again
  #
  play_again = input("Do you want to play again? (y/n) ")

  if play_again == "y":

    hangman()

  else:

    print("Thanks for playing!")

hangman()