# -*- coding: utf-8 -*-
"""About me - better structure -- Answers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRBcunUPKuJwwYllLoT6lv-qT4zaAleV
"""

def ask_followup(question, followup_question):

    response = input(question).strip().lower()

    if response == "yes":
        return input(followup_question).strip()

    elif response == "no":
        return "None"

# Collect user information
user_info = {
    "current_school": input("Where do you currently attend school? ").strip(),
    "school_activity": ask_followup("Do you participate in any school activities? (yes/no) ", "What activity? "),
    "license": ask_followup("Are you a licensed driver? (yes/no) ", "What car do you drive? "),
    "employed": ask_followup("Are you currently employed? (yes/no) ", "Who is the employer? "),
    "college": ask_followup("Are you planning on attending college? (yes/no) ", "What school? "),
}

print(user_info)